<a href="https://colab.research.google.com/github/Amey-Thakur/PYTHON-CRASH-COURSE/blob/main/PYTHON_CRASH_COURSE_DAY_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Day 5**

**Exceptions**

Exception is an abnormal condition which changes the flow of execution of the program.


**Handling the exceptions using try/except clause**

In [1]:
import sys

randomLst = ['a',0,2]

for entry in randomLst:
  try:
    #here are the suspicious statements
    print("The entry point is :", entry)

    r = 1/int(entry)    #this will generate exceptions
    break
  
  except:
    print("Oops! ",sys.exc_info()[0], "occured")
    print("Next entry")
    print()

print("The reciprocal of ",entry, " is ", r)

The entry point is : a
Oops!  <class 'ValueError'> occured
Next entry

The entry point is : 0
Oops!  <class 'ZeroDivisionError'> occured
Next entry

The entry point is : 2
The reciprocal of  2  is  0.5


# **Day 5 contd**

**Numpy**

Its package or module to perform scientific computing in python efficiently. It works only on numerical data.

In [2]:
#Numpy Arrays

#list of put volume data in lacs
put_vol = [52.89, 45.14, 63.84, 77.1, 74.6]

#list of call volume in lacs
call_vol = [49.41, 50.45, 59.11, 80.49, 65.11]

In [3]:
#lets install numpy in colab
!pip install -q numpy

In [4]:
#lets import numpy 
import numpy as np

n_put_vol = np.array(put_vol)

n_call_vol = np.array(call_vol)

#compute pcr
n_put_vol/n_call_vol

array([1.07043109, 0.89474727, 1.0800203 , 0.95788297, 1.14575334])

In [5]:
#lets create rank 1 array
a = np.array([1,2,3])
print(a, type(a))

[1 2 3] <class 'numpy.ndarray'>


In [6]:
#lets know the shape of the array
print(a.shape)

(3,)


In [7]:
#accessing the array elements
print(a[0], a[1],a[2])

1 2 3


In [8]:
#lets update array item
a[1] = 5

In [9]:
a

array([1, 5, 3])

In [10]:
#task: create a rank2 array
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [11]:
b.shape

(2, 3)

**Array creation using built in methods**

In [12]:
#zeros(shape, dtype): returns an array of given shape and dtype, filled with zeroes
#creating 1-d array
np.zeros(5) 

array([0., 0., 0., 0., 0.])

In [13]:
#creating a two dimensional array
np.zeros((3,5), dtype=np.int64)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [14]:
#task create an array filled with 1's of shape 3,5
#ones(shape, dtype): returns an array of given shape and dtype, filled with ones 
np.ones((3,5), dtype=np.int64)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [15]:
#create a constant array with 7 as item of shape 3,3
#full(shape, fill_value): returns an array of given shape and dtype, filled with fill_value given as parameter
np.full((3,3), 7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [16]:
#arange([start,] stop-1, [step]): This returns an array with evenly spaced values within a given interval
np.arange(5)

array([0, 1, 2, 3, 4])

In [17]:
np.arange(3,8)

array([3, 4, 5, 6, 7])

In [18]:
#array with an interval as step
np.arange(3,8, 0.5)

array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5])

In [19]:
#linspace(start, stop, num, endpoint): returns evenly spaced numbers over a specified interval
np.linspace(2.0, 3.0, num=10)

array([2.        , 2.11111111, 2.22222222, 2.33333333, 2.44444444,
       2.55555556, 2.66666667, 2.77777778, 2.88888889, 3.        ])

In [20]:
np.linspace(2.0, 3.0, num=10, endpoint=False)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [21]:
np.full((3,3), 7, dtype=np.float64)

array([[7., 7., 7.],
       [7., 7., 7.],
       [7., 7., 7.]])

In [22]:
#lets create an identity matrix
np.identity(5, dtype=np.int64) 

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [23]:
np.eye(4,k=2)

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

**Random  Sampling**

In [24]:
#rand():It is used to create an array of a given shape and populate it with random samples,
#from a uniform distribution over[0,1]. It takes only positive arguments
np.random.rand()

0.15139807316808418

In [25]:
#1-d array with 4 random values
np.random.rand(4)

array([0.25608656, 0.72676974, 0.04272135, 0.84104579])

In [26]:
#2-d array
np.random.rand(2,3)

array([[0.24464244, 0.93506252, 0.84278864],
       [0.79937173, 0.55466781, 0.0684792 ]])

In [27]:
#randn(): 
np.random.randn()

0.6917695088488307

In [28]:
np.random.randn(2,3)

array([[-0.30745373,  0.6245666 ,  0.25238399],
       [ 0.28543804,  0.04331394, -1.08720559]])

In [29]:
#randint():
#generating a random integer between 0 and 6
np.random.randint(6)

2

In [30]:
#generating 1-d array
np.random.randint(3,9, size=5)

array([5, 5, 7, 5, 3])

**Array attributes and Methods**

In [31]:
#ndim: this attribute dsiplays the number of dimensions of array
n_call_vol.ndim

1

In [32]:
n_put_vol.shape

(5,)

In [33]:
n_2d = np.array([put_vol, call_vol])

In [34]:
n_2d

array([[52.89, 45.14, 63.84, 77.1 , 74.6 ],
       [49.41, 50.45, 59.11, 80.49, 65.11]])

In [35]:
n_2d.shape

(2, 5)

In [36]:
n_2d.shape = (5,2)

In [37]:
n_2d.shape

(5, 2)

**Array Indexing**

Numpy offers several ways to index into arrays

In [38]:
#slicing()
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [39]:
#lets pull out a sub arry consisting of 2 rows and 1&2 column
b = a[:2,1:3]
b

array([[2, 3],
       [6, 7]])

In [40]:
#type conversion
x = np.array([1,2])
print(x.dtype)

int64


In [41]:
#lets force convert the data type
x = np.array([1,2], dtype=np.float64)
x.dtype

dtype('float64')

In [42]:
a[1:,1:]

array([[ 6,  7,  8],
       [10, 11, 12]])

In [43]:
#lets reshape our array
res = np.arange(12)

In [44]:
res

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [45]:
np.reshape(res, (3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [46]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]],dtype=np.float64)

x + y

array([[ 6.,  8.],
       [10., 12.]])

In [47]:
np.add(x,y)

array([[ 6.,  8.],
       [10., 12.]])

**Broadcasting**
Its a powerful mechanism that allows numpy to work with arrays of different shape when performing arithmetic operations.

In [48]:
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [49]:
#we want to add the constant vector to each row of the matrix
v = np.array([1,0,1])

In [50]:
#we want to add vector v to each row of the matrix x, storing the result in y
y = np.empty_like(x)

for i in range(4):
  y[i,:] = x[i,:] + v

#lets print the output
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
